### ISSUE TITLE
[E::parse_cigar] CIGAR length too long at position 1 (274808464H)

### ISSUE THREAD

**Issue by davidaray** [cgroza/GraffiTE#16] opened 2023-09-21 14:35 UTC
Me again. 

Managed to get the software to run but it only ran for four minutes before hitting this CIGAR error. 

A quick google search suggests that the read lengths are too long to handle (https://github.com/samtools/samtools/issues/1667).

However, I'm not dealing with reads, this is a job where I'm analyzing whole assemblies. I'm sure this is a mistake on my part somewhere given that the documentation specifically says graffiTE can be run using whole assemblies.

My command line:

```
nextflow run https://github.com/cgroza/GraffiTE \
   --assemblies cTho_assemblies.csv \
   --TE_library mammals.plus.covid_bats2.14072022.fa \
   --reference ../assemblies/cTho_A.fa \
   --graph_method pangenie \
   --genotype false \
   --cores 12 \
   --mammal \
   --svim_asm_threads 12 \
   --asm_divergence asm5
   --svim_asm_time 2h    
```

The error:
```

[-        ] process > svim_asm       -
[-        ] process > survivor_merge -
[-        ] process > repeatmask_VCF -
[-        ] process > tsd_prep       -
[-        ] process > tsd_search     -
[-        ] process > tsd_report     -

executor >  local (1)
[11/563cf2] process > svim_asm (1)   [  0%] 0 of 2
[-        ] process > survivor_merge -
[-        ] process > repeatmask_VCF -
[-        ] process > tsd_prep       -
[-        ] process > tsd_search     -
[-        ] process > tsd_report     -

executor >  local (2)
[12/90fee5] process > svim_asm (2)   [  0%] 0 of 2
[-        ] process > survivor_merge -
[-        ] process > repeatmask_VCF -
[-        ] process > tsd_prep       -
[-        ] process > tsd_search     -
[-        ] process > tsd_report     -
ERROR ~ Error executing process > 'svim_asm (1)'

Caused by:
  Process `svim_asm (1)` terminated with an error exit status (1)

Command executed:

  mkdir asm
  minimap2 -a -x asm5 --cs -r2k -t 12 -K 500M cTho_A.fa cTho_B.fa | samtools sort -m4G -@4 -o asm/asm.sorted.bam -
  samtools index asm/asm.sorted.bam
  svim-asm haploid --min_sv_size 100 --types INS,DEL --sample cTho_B asm/ asm/asm.sorted.bam cTho_A.fa
  sed 's/svim_asm\./cTho_B\.svim_asm\./g' asm/variants.vcf > cTho_B.vcf

Command exit status:
  1

Command output:
  (empty)

Command error:
  [M::mm_idx_gen::31.011*1.36] collected minimizers
  [M::mm_idx_gen::37.874*1.71] sorted minimizers
  [M::main::37.874*1.71] loaded/built the index for 812 target sequence(s)
  [M::mm_mapopt_update::40.498*1.66] mid_occ = 168
  [M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 812
  [M::mm_idx_stat::42.456*1.63] distinct minimizers: 161244371 (94.15% are singletons); average occurrences: 1.421; average spacing: 9.923; total length: 2273669687
  [E::parse_cigar] CIGAR length too long at position 1 (274808464H)
  [E::parse_cigar] CIGAR length too long at position 877 (272289946H)
  [E::parse_cigar] CIGAR length too long at position 4012 (275636627H)
  samtools sort: truncated file. Aborting
```

Any insight would be appreciated.

David

**Comment by cgroza** [comment] 2023-09-21 14:48
It seems that crash is in minimap2, due to the CIGAR exceeding a certain length.
We will try passing the -L flag to minimap2 and push a new commit, to see if it fixes the issue.

**Comment by davidaray** [comment] 2023-09-21 14:49
Please post when the new commit is made so I can try again. Thanks.

**Comment by cgroza** [comment] 2023-09-21 14:52
I pushed the commit in main.
Please let us know if it worked.

**Comment by cgroza** [comment] 2023-09-21 15:00
Otherwise, it seems minimap2 has difficulty aligning your genomes.
Perhaps you could experiment with different minimap2 versions or flags and identify a set of parameters that works for you?

**Comment by davidaray** [comment] 2023-09-21 18:10
I'm comparing three assemblies. Two are haplotypes of the same individual. The third is a not very great assembly from our recent work on the Zoonomia project. Species = Craseonycteris thonglongyai, the bumblebee bat. It's got a very diverse TE repertoire (https://academic.oup.com/mbe/article/40/5/msad092/7128099), which is why I chose this as a test.  The genome assemblies are typical mammal size, ~2.5 Gb. 

I'd hate to start altering your code by trying different versions of minimap. I would undoubtedly screw something up. 

Current progress. Tried the new commit by calling the github installation but it failed with the same error. 

Per a discussion with Clement over Slack, I've recloned the repository and am trying again with the local installation rather than calling from github.

.... time passes....

If failed again with the same error. Any need to regrab the singularity container? Clement says that it wasn't touched so I wouldn't think so.

I do see that the -L is now included in the minimap2 command. 

```
minimap2 -L -a -x asm5 --cs -r2k -t 12 -K 500M cTho_A.fa cTho_B.fa | samtools sort -m4G -@4 -o asm/asm.sorted.bam -

```
 So, that doesn't appear to fix the issue.

**Comment by cgroza** [comment] 2023-09-21 18:12
You would not need to change the pipeline code.
You could copy the minimap2 command and try it yourself with different tweaks until it accepts the genome.
Otherwise, this is a bug in minimap2 and we would need to update the image to include the minimap2 version without this bug.

**Comment by davidaray** [comment] 2023-09-21 18:13
I'm trying something else at the moment. I'll give that a try if it fails again.

**Comment by davidaray** [comment] 2023-09-21 19:29
Update. I'm comparing cTho_A.fa (reference) to cTho_B.fa (a second haplotype of the same individual) and CraTho.fa (a second individual and lower quality assembly. A and B are very high quality assemblies, each with several scaffolds >200Mb. I've split the three largest scaffolds from B into halves and have reconstituted the assembly after replacing the original scaffolds with those halves. It's running now.

... waiting....

Well, according to the nextflow log, we've made it past the original crash. I'll update a bit later if it crashes again.

**Comment by davidaray** [comment] 2023-09-21 19:36
Yes! In previous runs, only one vcf (for CraTho) was being generated. A second one based on the revised cTho_B assembly has now appeared. 

I'm not sure if this is a generally applicable problem but it might be worth updated in the readme with this caveat, no scaffolds >200 Mb for the comparison genome assemblies.

**Comment by cgroza** [comment] 2023-09-21 19:39
Yes we should add it. We ourselves never encountered this issue, since it seems to be a result of an obscure limitation in htslib which samtools uses.

**Comment by dtx282000** [comment] 2023-12-26 00:16
I have encountered the same error.  I have also added the -L parameter when using minimap2. So, how can I resolve it?
<img width="1149" alt="image" src="https://github.com/cgroza/GraffiTE/assets/24269804/fcee8744-9cd0-41ed-81b5-6615e91d658f">

**Comment by cgroza** [comment] 2023-12-27 15:43
Hi,

This problem was actually caused by genome assemblies that were scaffolded and the gaps masked with long runs of N.
You may fix this by breaking the gaps into separate contigs.

Cristian Groza

**Comment by dtx282000** [comment] 2023-12-31 03:29
Yes, you are correct.  I followed your suggestion and fixed them.

**Comment by clemgoub** [comment] 2024-05-23 23:24
@davidaray, I am closing the issue for now, though if you still encounter the problem, please let us know and reopen!

Cheers,

Clément

**Closed by clemgoub** 2024-05-23 23:24 UTC
